version: "3"

services:
  mysql:
    image: mysql/mysql-server:5.6
    # restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 0129
      MYSQL_DATABASE: s002
    container_name: test-mysql
    ports:
    - 3306:3306
    networks:
      default:
    # volumes:
      # - ./data:/var/lib/mysql
      # - ./config/mysql.cnf:/etc/my.cnf
      # - ./init:/docker-entrypoint-initdb.d/